### ISSUE TITLE
Populate is not working at all

### ISSUE THREAD

**Issue by AndonMitev** [aravindnc/mongoose-paginate-v2#113]
Populate is not working at all

**Comment by aravindnc** [comment]
@AndonMitev Please share your issue in detail.

**Comment by venusdharan** [comment]
I had the same problem , but gone through the collection and found that some of the docs, which were old ones did not have the ref part(hardcoded values), as I was testing, and after removing those the populate works perfectly. is there a way to prevent this like ignore if ref is not present rather than just throwing error.

**Comment by aravindnc** [comment]
@venusdharan So are you getting an error if the ref. is invalid? I guess it should return null if the reference doesn't exist.

**Comment by venusdharan** [comment]
yes i am getting error when  ref is invalid, initially i wrapped it in try catch block and took a while figure it out  to edit some documents and give it a try and it worked.

**Comment by aravindnc** [comment]
@venusdharan Thanks. Can you u try to use populate without using paginate plugin and see whether it returns error returns or not.

**Comment by aravindnc** [comment]
@venusdharan Did you get a chance to take a look at this.

**Comment by aravindnc** [comment]
@venusdharan Please reopen if the issue exists in the new version.
