### ISSUE TITLE
Passing of additional data that can be used to ignore already paginated data

### ISSUE THREAD

**Issue by hasan-li** [aravindnc/mongoose-paginate-v2#118]
**Describe the bug**
There is the possibility that the same data will be loaded twice on next page

**To Reproduce**
1. get 3 values from db (`page: 1; limit: 3`): `A, B, C`
2. in a meantime write 1 new data item `D` into the collection
3. get next 3 values from db (`page: 2; limit: 3`): `C, D, E`
4. as you can see when adding new data `C` has been pushed down and now for the next pagination in step 3 we are loading it a second time
 
**Expected behavior**
By passing some additional data into query/options (like id of last paginated item from db) we could solve duplicated appearance of data

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Comment by aravindnc** [comment]
@hasan-li That's strange. Are you sure you are getting duplicate data while paginating ?

**Comment by hasan-li** [comment]
@aravindnc yes, I double-checked it right now by manually inserting a new doc before calling the second page. So the last document is being shifted to the next page

**Comment by aravindnc** [comment]
@hasan-li Thanks. I will take a look and get back.

**Comment by turshija** [comment]
I'm having the same issue, came here to report it and seeing this thread.
In my situation, it happens only when sorting by a value which is a number, and only when those documents share same value with other documents. In my case I have a lot of documents which have value 0, so one of the documents just appears on two pages (but only when doing descending sort).
I've confirmed that its not an issue with frontend, because I'm getting same data directly from API.
My options are `lean: true, leanWithId: false, customLabels: { docs: 'data' }`  and for pagination I'm sending `page: 1, limit: 10, sort: { totalValueUi: -1 }`

![Screen Capture on 2021-05-24 at 12-22-18](https://user-images.githubusercontent.com/933433/119336770-4f7e7e80-bc8e-11eb-973b-da9291425060.gif)

**Comment by aravindnc** [comment]
@turshija That's great. Thanks.
