### ISSUE TITLE
Sort doesn't work with mongoose-paginate (but works with vanilla mongoose)

### ISSUE THREAD

**Issue by JoshuaPerk** [aravindnc/mongoose-paginate-v2#145]
I have a collection of calendar `Events` and in their schema is a `start` key which holds a proper date. If I run a vanilla mongoose query such as...
```js
Event.find(filter).sort( { start: 1 } ).limit(250)
```
...as expected, I get a list of events, sorted oldest to newest.

However, when I run...
```js
const options = {
   sort: 'start'
   // or sort: { start: 1 }
}
Event.paginate(filter, options)
```
...I successfully have paginated results returned; however, they're not in any specific order.

I've attempted to make `start` an index at both the field and schema level but to no avail. Am I missing a step or syntax?

**Comment by trancephorm** [comment]
I just came from mongoose-aggregate-paginate-v2 here because it seems it's bugged when it comes to sorting, and now I'm reading this. Please if someone can confirm if this is a confirmed bug?

Actually I realised I don't need aggregation in my query and this paginate-v2 would suit me really well because it has same output fields as aggregate version, so I don't have to change my frontend. But I do need sorting of paginated results pretty badly...

**Comment by aravindnc** [comment]
@JoshuaPerk Seems sorting issue is happening for random users. I've tested with different scenarios and didn't get any issues till now.

**Comment by mryraghi** [comment]
I'm also getting this issue, is there any workaround or fix coming? Thanks

**Comment by divyeshdhokiya** [comment]
Same issue. any luck so far?

**Comment by Djibdjib** [comment]
Same issue here... thx to find a solution, plz

**Comment by maxis7567** [comment]
I have problems with sort too
for me sort works page to page

**Comment by orimdominic** [comment]
What I tried here that worked for me was including `_id` in the sort fields

**Comment by aravindnc** [comment]
Please reopen if the issue exists.
